{% set version = "1.0.0" %}
{% set name = "LMDB" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name|lower }}/archive/refs/tags/{{ name }}_{{ version }}.tar.gz
  sha256: 44a5ec3a8d71b4287244c538ee80a95e2af40b1a4ee04553359f044c7939734a
  patches:
    - patches/mdb_msvc_fixes.patch
    - patches/0001-fix-makefile.patch  # [unix]
    - patches/getopt_win.patch  # [win]
    - patches/getopt_win_drop.patch  # [win]
    - patches/ssize_t.patch  # [win]

build:
  number: 0
  run_exports:
    # good backwards compatibility
    # https://abi-laboratory.pro/tracker/timeline/lmdb/
    - {{ pin_subpackage('lmdb') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake  # [win]
    - make  # [not win]

test:
  requires:
    - conda-build
  commands:
    - mdb_copy -V
    - mdb_drop -V
    - mdb_dump -V
    - mdb_load -V
    - mdb_stat -V
    - if not exist %LIBRARY_INC%\\lmdb.h    exit 1  #  [win]
    - if not exist %LIBRARY_INC%\\midl.h    exit 1  #  [win]
    - if not exist %LIBRARY_LIB%\\lmdb.lib  exit 1  #  [win]
    - if not exist %LIBRARY_BIN%\\lmdb.dll  exit 1  #  [win]
    - conda inspect linkages -p $PREFIX lmdb  # [unix]

about:
  home: https://www.symas.com/symas-embedded-database-lmdb
  license: OLDAP-2.8
  license_file: libraries/liblmdb/LICENSE
  license_family: other
  summary: A high-performance embedded transactional key-value store database.
  description: |
    Symas LMDB is an extraordinarily fast, memory-efficient database developed
    for the Symas OpenLDAP Project. With memory-mapped files, it has the read
    performance of a pure in-memory database while retaining the persistence of
    standard disk-based databases.
  doc_url: https://www.symas.com/symas-embedded-database-lmdb
  dev_url: https://github.com/LMDB/lmdb

extra:
  recipe-maintainers:
    - jakirkham
