{% set version = "0.9.29" %}

package:
  name: lmdb
  version: {{ version }}

source:
  fn: LMDB_{{ version }}.tar.gz
  url: https://github.com/LMDB/lmdb/archive/LMDB_{{ version }}.tar.gz
  sha1: abb4dd93c66732054d12a0e30a965f83306112d1
  patches:
    - 0001-fix-makefile.patch   # [unix]
    - getopt_win.patch          # [win]
    - ssize_t.patch             # [win]

build:
  number: 0
  run_exports:
    # good backwards compatibility
    # https://abi-laboratory.pro/tracker/timeline/lmdb/
    - {{ pin_subpackage('lmdb') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake         # [win]
    - msinttypes    # [win and py<35]
    - make          # [not win]

test:
  commands:
    - mdb_copy -V
    - mdb_dump -V
    - mdb_load -V
    - mdb_stat -V

    - if not exist %LIBRARY_INC%\\lmdb.h    exit 1  #  [win]
    - if not exist %LIBRARY_INC%\\midl.h    exit 1  #  [win]
    - if not exist %LIBRARY_LIB%\\lmdb.lib  exit 1  #  [win]
    - if not exist %LIBRARY_BIN%\\lmdb.dll  exit 1  #  [win]
    - conda inspect linkages -p $PREFIX lmdb  # [unix]

about:
  home: https://symas.com/lightning-memory-mapped-database/
  license: OpenLDAP Public License and BSD 3-clause
  license_file: libraries/liblmdb/LICENSE
  license_family: BSD
  summary: A high-performance embedded transactional key-value store database.
  description: |
    Symas LMDB is an extraordinarily fast, memory-efficient database developed
    for the Symas OpenLDAP Project. With memory-mapped files, it has the read
    performance of a pure in-memory database while retaining the persistence of
    standard disk-based databases.
  doc_url: http://www.lmdb.tech/doc/

extra:
  recipe-maintainers:
    - jakirkham
