travis:
  secure:
    BINSTAR_TOKEN: XFIYY4bsKl1GWDc8oAfuoL23DGYJgAJLAkStcxri3O3i6dwGlTQPMGldYr14o5fobU9N3jXfaPAfG1PuEIfBWZSi/rmc+MSbXiiuyxYNZSdN8bnKn+dLDoSmqR/FK5bLlxpTX01d53Nvmfa0bUd6ve+4zYMUm4FwuC4oZTiL4QxaWr7shR82xGgxUjlwt2dqSPmFyzUKip5V0xbpjplWtBxeE8QERbsHxD26aopmcuFYIdxKTOUhcXk46sksXXxJANvODniCjqPWnWE8Yx2XjOznQAKMkbmstLqR7wL6xudwcEtVgwqQpqyE9sjqneO6wyRQv+FRi4YVYMi7EFiB+jGrX9OKPheSJ3YgQa1RQY2bIWax2HTRQhoitdt0+45k90HH7CSTliwZiqf1Dp7hGvktzIWrO939yAcs8oQuiX6wXiKy26zfwKs96llUdtxNfVGD8ktv1k7UqZ7nQ2OfbxQbd7S9OqT/peKB2/VQK8o06XfvshTKcD7C4JUub4pg9AOwAPt8Svts5MufSquVlLuwr8CwaUTJN2BWb18XBgU5p/DFrqTWd6Lw8aPQdwDaOlxKzchkWTtbXrCSEEuH04KJHLUUHF55Rke8To2x6pIzz8z29BYzJz1d1jnltTV4cV1XolIHPg6AAqM8RFOV1rj3d9qsYShDrM0XDMmu47U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
